
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Student : Luban.BeanBase
{
    public Student(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
        { if(!_buf["address"].IsString) { throw new SerializationException(); }  Address = _buf["address"]; }
    }

    public static Student DeserializeStudent(JSONNode _buf)
    {
        return new Student(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 年龄
    /// </summary>
    public readonly int Age;
    /// <summary>
    /// 服务器用测试
    /// </summary>
    public readonly string Address;
   
    public const int __ID__ = -214492645;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "age:" + Age + ","
        + "address:" + Address + ","
        + "}";
    }
}

}

