
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbWeapon TbWeapon {get; }
    public TbStudent TbStudent {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbWeapon = new TbWeapon(loader("tbweapon"));
        TbStudent = new TbStudent(loader("tbstudent"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbWeapon.ResolveRef(this);
        TbStudent.ResolveRef(this);
    }
}

}
